version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: core-js
    versions:
    - 3.11.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.16
    - 7.13.13
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.2
    - 5.2.0
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.10
    - 24.1.9
    - 24.2.0
    - 24.2.1
    - 24.3.2
  - dependency-name: "@babel/plugin-transform-runtime"
    versions:
    - 7.12.13
    - 7.13.2
    - 7.13.8
  - dependency-name: "@babel/runtime"
    versions:
    - 7.13.8
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.16
    - 7.13.8
  - dependency-name: danger
    versions:
    - 10.6.1
